version: '3.8'
services:
  db:
    image: mysql:5.7.32
    restart: always
    environment:
      MYSQL_DATABASE: "${DATABASE_NAME}"
      MYSQL_USER: "${DATABASE_USER}"
      MYSQL_PASSWORD: "${DATABASE_PASS}"
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  backend:
    build: ./backend
    environment:
      DATABASE_NAME: "${DATABASE_NAME}"
      DATABASE_USER: "${DATABASE_USER}"
      DATABASE_PASS: "${DATABASE_PASS}"
      DATABASE_HOST: "db"
      DATABASE_PORT: "3306"
      WAIT_HOSTS: "db:3306"
      ALLOWED_HOSTS: "localhost"
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - db
volumes:
  my-db:
